version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
