version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - type: bind
        source: ./src
        target: /app/code
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ls code

  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

