version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    image: kp_oop:latest
    ports:
      - "8080:8080"
    command: [ "http-server", "dist" ]

  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
