version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    working_dir: /app
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true

  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    working_dir: /app
    volumes:
      - ./server/src:/app/src
    ports:
      - "8081:8081"
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["yarn", "start"]

  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    ports:
      - "8082:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DB_HOST: db
    # command: ["/bin/bash", "-c", "su - postgres -c pg_ctl start"]
volumes:
  pgdata:
